name: Test Cron

on:
  schedule:
    - cron: "*/5 * * * *" # 5分ごとに実行
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Cron job is running!"
